#ifndef ELECTRONICCOMPONENT_GLOBAL_H
#define ELECTRONICCOMPONENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ELECTRONICCOMPONENT_LIBRARY)
#  define ELECTRONICCOMPONENT_EXPORT Q_DECL_EXPORT
#else
#  define ELECTRONICCOMPONENT_EXPORT Q_DECL_IMPORT
#endif

#endif // ELECTRONICCOMPONENT_GLOBAL_H
